// Generated by Selenium IDE
// const { Builder, By, Key, until } = require('selenium-webdriver')

const assert = require('assert')
const {Builder,until,By} = require("selenium-webdriver");
const chromeDriver = require("selenium-webdriver/chrome");

//npx mocha --parallel searchTest.js
describe('SearchTest', function() {
  this.timeout(50000)
  let driver
  let vars
  const chromeOptions = new chromeDriver.Options();
  //chrome 브라우저 옵션
  // chromeOptions.addArguments("--headless");
  // chromeOptions.addArguments("--disable-gpu");
  // chromeOptions.addArguments("--no-sandbox");
  // beforeEach(async function() {
  before(async function() {
    driver = await new Builder().forBrowser('chrome')
        .setChromeOptions(chromeOptions)
        .build()
    vars = {}
    await driver.get("http://todo.wooyu.world/")
    // await driver.get("http://localhost:8181/")
  })
  // afterEach(async function() {
  after(async function() {
    await driver.quit();
  })
// describe('SearchTest', function() {
//   this.timeout(30000)
//   let driver
//   let vars
//   beforeEach(async function() {
//     driver = await new Builder().forBrowser('chrome').build()
//     vars = {}
//   })
//   afterEach(async function() {
//     await driver.quit();
//   })
  it('TC00000061', async function() {

    vars["check"] = await driver.executeScript("return 1")
    const times = 1
    for(let i = 0; i < times; i++) {
      await driver.findElement(By.css(".bi-pencil-fill")).click()
      // 모달 나타날때까지 기다림
      await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
      await driver.findElement(By.id("exampleModalLabel")).click()
      await driver.findElement(By.id("exampleModalLabel")).sendKeys("loop title" + vars["check"])
      await driver.findElement(By.id("addDate")).click()
      await driver.findElement(By.id("addDate")).sendKeys("002024-03-09")
      await driver.findElement(By.id("modalSaveBtn")).click()
      vars["check"] = await driver.executeScript("return arguments[0] + 1", vars["check"])
    }
    await driver.navigate().refresh();
    await driver.sleep(2000);
    await driver.wait(until.elementTextIs(await driver.findElement(By.css(".title")), 'To do list'), 30000)
    // //여기까지 전제조건
    await driver.navigate().refresh();
    await driver.sleep(2000);
    await driver.wait(until.elementIsVisible(await driver.findElement(By.css(".card-body"))), 3000)

    await driver.findElement(By.css(".searchIcon")).click()
    assert(await driver.switchTo().alert().getText() == "내용 or 날짜를 입력하세요.")
    await driver.switchTo().alert().accept()

    await driver.navigate().refresh();
    await driver.sleep(2000);
    // // 삭제하기
    await driver.findElement(By.name("deleteBtn")).click()
    assert(await driver.switchTo().alert().getText() == "삭제하시겠습니까?")
    await driver.switchTo().alert().accept()
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(!elements.length)
    }
  })
  it('TC00000062', async function() {
    vars["check"] = await driver.executeScript("return 1")
    const times = 1
    for(let i = 0; i < times; i++) {
      await driver.findElement(By.css(".bi-pencil-fill")).click()
      // 모달 나타날때까지 기다림
      await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
      await driver.findElement(By.id("exampleModalLabel")).click()
      await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title" + vars["check"])
      await driver.findElement(By.id("addDate")).click()
      await driver.findElement(By.id("addDate")).sendKeys("002024-03-09")
      await driver.findElement(By.id("modalSaveBtn")).click()
      vars["check"] = await driver.executeScript("return arguments[0] + 1", vars["check"])
    }
    await driver.wait(until.elementTextIs(await driver.findElement(By.css(".title")), 'To do list'), 30000)
    // //여기까지 전제조건
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(elements.length)
    }
    await driver.findElement(By.id("searchTitle")).click()
    await driver.findElement(By.id("searchTitle")).sendKeys("search")
    await driver.findElement(By.css(".searchIcon")).click()
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(!elements.length)
    }
    // // 삭제하기
    console.log("삭제하기")
    await driver.get("http://todo.wooyu.world/")
    await driver.findElement(By.name("deleteBtn")).click()
    assert(await driver.switchTo().alert().getText() == "삭제하시겠습니까?")
    await driver.switchTo().alert().accept()
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(!elements.length)
    }
  })
  it('TC00000063', async function() {
    const times = 1
    for(let i = 0; i < times; i++) {
      await driver.findElement(By.css(".bi-pencil-fill")).click()
      // 모달 나타날때까지 기다림
      await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
      await driver.findElement(By.id("exampleModalLabel")).click()
      await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title")
      await driver.findElement(By.id("addDate")).click()
      await driver.findElement(By.id("addDate")).sendKeys("002024-03-09")
      await driver.findElement(By.id("modalSaveBtn")).click()
      await driver.findElement(By.css(".bi-pencil-fill")).click()
      // 모달 나타날때까지 기다림
      await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
      await driver.findElement(By.id("exampleModalLabel")).click()
      await driver.findElement(By.id("exampleModalLabel")).sendKeys("to do list")
      await driver.findElement(By.id("addDate")).click()
      await driver.findElement(By.id("addDate")).sendKeys("002024-03-10")
      await driver.findElement(By.id("modalSaveBtn")).click()
    }
    await driver.wait(until.elementTextIs(await driver.findElement(By.css(".title")), 'To do list'), 30000)
    // //여기까지 전제조건
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(elements.length)
    }
    await driver.findElement(By.id("searchTitle")).click()
    await driver.findElement(By.id("searchTitle")).sendKeys("test title")
    {
      const value = await driver.findElement(By.id("searchTitle")).getAttribute("value")
      assert(value == "test title")
    }
    await driver.findElement(By.css(".searchIcon")).click()
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css("span:nth-child(3)")).getText() == "test title")
    // // 삭제하기
    console.log("삭제하기")
    await driver.get("http://todo.wooyu.world/")
    const DeleteTimes = 2
    for(let i = 0; i < DeleteTimes; i++) {
      await driver.findElement(By.name("deleteBtn")).click()
      assert(await driver.switchTo().alert().getText() == "삭제하시겠습니까?")
      await driver.switchTo().alert().accept()
    }
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(!elements.length)
    }
  })
  it('TC00000064', async function() {
    const times = 1
    for(let i = 0; i < times; i++) {
      await driver.findElement(By.css(".bi-pencil-fill")).click()
      // 모달 나타날때까지 기다림
      await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
      await driver.findElement(By.id("exampleModalLabel")).click()
      await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title")
      await driver.findElement(By.id("addDate")).click()
      await driver.findElement(By.id("addDate")).sendKeys("002024-03-11")
      await driver.findElement(By.id("modalSaveBtn")).click()
      await driver.findElement(By.css(".bi-pencil-fill")).click()
      // 모달 나타날때까지 기다림
      await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
      await driver.findElement(By.id("exampleModalLabel")).click()
      await driver.findElement(By.id("exampleModalLabel")).sendKeys("to do list")
      await driver.findElement(By.id("addDate")).click()
      await driver.findElement(By.id("addDate")).sendKeys("002024-03-12")
      await driver.findElement(By.id("modalSaveBtn")).click()
    }
    await driver.wait(until.elementTextIs(await driver.findElement(By.css(".title")), 'To do list'), 30000)
    // //여기까지 전제조건
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(elements.length)
    }
    await driver.findElement(By.id("searchTitle")).click()
    await driver.findElement(By.id("searchTitle")).sendKeys("test ti")
    await driver.findElement(By.css(".searchIcon")).click()
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css("span:nth-child(3)")).getText() == "test title")
    // //test ti 포함하는지 mcoah.js로 작성하여 확인
    console.log("test ti 포함하는지 mcoah.js로 작성하여 확인")
    // // 삭제하기
    console.log("삭제하기")
    await driver.get("http://todo.wooyu.world/")
    const DeleteTimes = 2
    for(let i = 0; i < DeleteTimes; i++) {
      await driver.findElement(By.name("deleteBtn")).click()
      assert(await driver.switchTo().alert().getText() == "삭제하시겠습니까?")
      await driver.switchTo().alert().accept()
    }
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(!elements.length)
    }
  })
  it('TC00000065', async function() {
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title65")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-11")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.get("http://todo.wooyu.world/")
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title65")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-12")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.wait(until.elementTextIs(await driver.findElement(By.css(".title")), 'To do list'), 30000)
    // //여기까지 전제조건
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(elements.length)
    }
    await driver.findElement(By.id("searchTitle")).click()
    await driver.findElement(By.id("searchTitle")).sendKeys("test title65")
    await driver.findElement(By.css(".searchIcon")).click()
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".card:nth-child(1) span")).getText() == "test title65")
    assert(await driver.findElement(By.css(".card:nth-child(2) span")).getText() == "test title65")
    // // 삭제하기
    console.log("삭제하기")
    await driver.get("http://todo.wooyu.world/")
    const times = 2
    for(let i = 0; i < times; i++) {
      await driver.findElement(By.name("deleteBtn")).click()
      assert(await driver.switchTo().alert().getText() == "삭제하시겠습니까?")
      await driver.switchTo().alert().accept()
    }
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(!elements.length)
    }
  })
  it('TC00000066', async function() {
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title66")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-11")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.get("http://todo.wooyu.world/")
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title66")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-12")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.wait(until.elementTextIs(await driver.findElement(By.css(".title")), 'To do list'), 30000)
    // //여기까지 전제조건
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(elements.length)
    }
    await driver.findElement(By.id("searchTitle")).click()
    await driver.findElement(By.id("searchTitle")).sendKeys("test ti")
    await driver.findElement(By.css(".searchIcon")).click()
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".card:nth-child(1) span")).getText() == "test title66")
    assert(await driver.findElement(By.css(".card:nth-child(2) span")).getText() == "test title66")
    // //test ti 포함하는지 mcoah.js로 작성하여 확인
    console.log("test ti 포함하는지 mcoah.js로 작성하여 확인")
    // // 삭제하기
    console.log("삭제하기")
    await driver.get("http://todo.wooyu.world/")
    const times = 2
    for(let i = 0; i < times; i++) {
      await driver.findElement(By.name("deleteBtn")).click()
      assert(await driver.switchTo().alert().getText() == "삭제하시겠습니까?")
      await driver.switchTo().alert().accept()
    }
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(!elements.length)
    }
  })
  it('TC00000067', async function() {
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title67")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-11")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.get("http://todo.wooyu.world/")
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("to do6 list7")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-11")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.wait(until.elementTextIs(await driver.findElement(By.css(".title")), 'To do list'), 30000)
    // //여기까지 전제조건
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(elements.length)
    }
    await driver.findElement(By.id("searchTitle")).click()
    await driver.findElement(By.id("searchTitle")).sendKeys("test title67")
    await driver.findElement(By.css(".searchIcon")).click()
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(!elements.length)
    }
    assert(await driver.findElement(By.css(".card:nth-child(1) span")).getText() == "test title67")
    // // 삭제하기
    console.log("삭제하기")
    await driver.get("http://todo.wooyu.world/")
    const times = 2
    for(let i = 0; i < times; i++) {
      await driver.findElement(By.name("deleteBtn")).click()
      assert(await driver.switchTo().alert().getText() == "삭제하시겠습니까?")
      await driver.switchTo().alert().accept()
    }
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(!elements.length)
    }
  })
  it('TC00000068', async function() {
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title68")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-11")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.get("http://todo.wooyu.world/")
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("to do6 list8")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-11")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.wait(until.elementTextIs(await driver.findElement(By.css(".title")), 'To do list'), 30000)
    // //여기까지 전제조건
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(elements.length)
    }
    await driver.findElement(By.id("searchTitle")).click()
    await driver.findElement(By.id("searchTitle")).sendKeys("test ti")
    await driver.findElement(By.css(".searchIcon")).click()
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(!elements.length)
    }
    assert(await driver.findElement(By.css(".card:nth-child(1) span")).getText() == "test title68")
    // //test ti 포함하는지 mcoah.js로 작성하여 확인
    console.log("test ti 포함하는지 mcoah.js로 작성하여 확인")
    // // 삭제하기
    console.log("삭제하기")
    await driver.get("http://todo.wooyu.world/")
    const times = 2
    for(let i = 0; i < times; i++) {
      await driver.findElement(By.name("deleteBtn")).click()
      assert(await driver.switchTo().alert().getText() == "삭제하시겠습니까?")
      await driver.switchTo().alert().accept()
    }
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(!elements.length)
    }
  })
  it('TC00000069', async function() {
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title69")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-11")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.get("http://todo.wooyu.world/")
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title69")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-11")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.wait(until.elementTextIs(await driver.findElement(By.css(".title")), 'To do list'), 30000)
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    // //여기까지 전제조건
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(elements.length)
    }
    await driver.findElement(By.id("searchTitle")).click()
    await driver.findElement(By.id("searchTitle")).sendKeys("test title69")
    await driver.findElement(By.css(".searchIcon")).click()
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".card:nth-child(1) span")).getText() == "test title69")
    assert(await driver.findElement(By.css(".card:nth-child(2) span")).getText() == "test title69")
    // // 삭제하기
    console.log("삭제하기")
    await driver.get("http://todo.wooyu.world/")
    const times = 2
    for(let i = 0; i < times; i++) {
      await driver.findElement(By.name("deleteBtn")).click()
      assert(await driver.switchTo().alert().getText() == "삭제하시겠습니까?")
      await driver.switchTo().alert().accept()
    }
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(!elements.length)
    }
  })
  it('TC00000070', async function() {
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title70")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-11")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.get("http://todo.wooyu.world/")
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title70")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-11")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.wait(until.elementTextIs(await driver.findElement(By.css(".title")), 'To do list'), 30000)
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    // //여기까지 전제조건
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(elements.length)
    }
    await driver.findElement(By.id("searchTitle")).click()
    await driver.findElement(By.id("searchTitle")).sendKeys("test ti")
    await driver.findElement(By.css(".searchIcon")).click()
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".card:nth-child(1) span")).getText() == "test title70")
    assert(await driver.findElement(By.css(".card:nth-child(2) span")).getText() == "test title70")
    // //test ti 포함하는지 mcoah.js로 작성하여 확인
    console.log("test ti 포함하는지 mcoah.js로 작성하여 확인")
    // // 삭제하기
    console.log("삭제하기")
    await driver.get("http://todo.wooyu.world/")
    const times = 2
    for(let i = 0; i < times; i++) {
      await driver.findElement(By.name("deleteBtn")).click()
      assert(await driver.switchTo().alert().getText() == "삭제하시겠습니까?")
      await driver.switchTo().alert().accept()
    }
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(!elements.length)
    }
  })
  it('TC00000071', async function() {
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title71")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-11")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.get("http://todo.wooyu.world/")
    await driver.wait(until.elementTextIs(await driver.findElement(By.css(".title")), 'To do list'), 30000)
    // //여기까지 전제조건
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    await driver.findElement(By.id("searchDate")).click()
    await driver.findElement(By.id("searchDate")).sendKeys("002024-04-11")
    await driver.findElement(By.css(".searchIcon")).click()
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(!elements.length)
    }
    // // 삭제하기
    console.log("삭제하기")
    await driver.get("http://todo.wooyu.world/")
    await driver.findElement(By.name("deleteBtn")).click()
    assert(await driver.switchTo().alert().getText() == "삭제하시겠습니까?")
    await driver.switchTo().alert().accept()
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(!elements.length)
    }
  })
  it('TC00000072', async function() {
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title72")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-11")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.get("http://todo.wooyu.world/")
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("to do7 list2")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-12")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.wait(until.elementTextIs(await driver.findElement(By.css(".title")), 'To do list'), 30000)
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    // //여기까지 전제조건
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(elements.length)
    }
    await driver.findElement(By.id("searchDate")).click()
    await driver.findElement(By.id("searchDate")).sendKeys("002024-03-11")
    // // search date value는 002024
    {
      const value = await driver.findElement(By.id("searchDate")).getAttribute("value")
      assert(value == "002024-03-11")
    }
    await driver.findElement(By.css(".searchIcon")).click()
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(!elements.length)
    }
    assert(await driver.findElement(By.css(".card:nth-child(1) span")).getText() == "test title72")
    await driver.findElement(By.css(".btn-primary:nth-child(1)")).click()
    // //모달 date value는 2024
    {
      const value = await driver.findElement(By.id("addDate")).getAttribute("value")
      assert(value == "2024-03-11")
    }
    await driver.findElement(By.css(".btn-close")).click()
    // // 삭제하기
    console.log("삭제하기")
    await driver.get("http://todo.wooyu.world/")
    const times = 2
    for(let i = 0; i < times; i++) {
      await driver.findElement(By.name("deleteBtn")).click()
      assert(await driver.switchTo().alert().getText() == "삭제하시겠습니까?")
      await driver.switchTo().alert().accept()
    }
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(!elements.length)
    }
  })
  it('TC00000073', async function() {
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title73")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-11")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.get("http://todo.wooyu.world/")
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title73")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-12")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.wait(until.elementTextIs(await driver.findElement(By.css(".title")), 'To do list'), 30000)
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    // //여기까지 전제조건
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(elements.length)
    }
    await driver.findElement(By.id("searchDate")).click()
    await driver.findElement(By.id("searchDate")).sendKeys("002024-03-11")
    await driver.findElement(By.css(".searchIcon")).click()
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(!elements.length)
    }
    assert(await driver.findElement(By.css(".card:nth-child(1) span")).getText() == "test title73")
    await driver.findElement(By.css(".btn-primary:nth-child(1)")).click()
    // //모달 date value는 2024
    {
      const value = await driver.findElement(By.id("addDate")).getAttribute("value")
      assert(value == "2024-03-11")
    }
    await driver.findElement(By.css(".btn-close")).click()
    // // 삭제하기
    console.log("삭제하기")
    await driver.get("http://todo.wooyu.world/")
    const times = 2
    for(let i = 0; i < times; i++) {
      await driver.findElement(By.name("deleteBtn")).click()
      assert(await driver.switchTo().alert().getText() == "삭제하시겠습니까?")
      await driver.switchTo().alert().accept()
    }
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(!elements.length)
    }
  })
  it('TC00000074', async function() {
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title74")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-11")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.get("http://todo.wooyu.world/")
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("to do7 list4")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-11")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.wait(until.elementTextIs(await driver.findElement(By.css(".title")), 'To do list'), 30000)
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    // //여기까지 전제조건
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(elements.length)
    }
    await driver.findElement(By.id("searchDate")).click()
    await driver.findElement(By.id("searchDate")).sendKeys("002024-03-11")
    await driver.findElement(By.css(".searchIcon")).click()
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".card:nth-child(1) span")).getText() == "test title74")
    assert(await driver.findElement(By.css(".card:nth-child(2) span")).getText() == "to do7 list4")
    await driver.findElement(By.css(".btn-primary:nth-child(1)")).click()
    // //모달 date value는 2024
    {
      const value = await driver.findElement(By.id("addDate")).getAttribute("value")
      assert(value == "2024-03-11")
    }
    await driver.findElement(By.css(".btn-secondary")).click()
    await driver.findElement(By.css(".card:nth-child(2) .btn-primary")).click()
    {
      const value = await driver.findElement(By.id("addDate")).getAttribute("value")
      assert(value == "2024-03-11")
    }
    await driver.findElement(By.css(".btn-close")).click()
    // // 삭제하기
    console.log("삭제하기")
    await driver.get("http://todo.wooyu.world/")
    const times = 2
    for(let i = 0; i < times; i++) {
      await driver.findElement(By.name("deleteBtn")).click()
      assert(await driver.switchTo().alert().getText() == "삭제하시겠습니까?")
      await driver.switchTo().alert().accept()
    }
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(!elements.length)
    }
  })
  it('TC00000075', async function() {
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title75")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-12")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.get("http://todo.wooyu.world/")
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title75")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-12")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.wait(until.elementTextIs(await driver.findElement(By.css(".title")), 'To do list'), 30000)
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    // //여기까지 전제조건
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(elements.length)
    }
    await driver.findElement(By.id("searchDate")).click()
    await driver.findElement(By.id("searchDate")).sendKeys("002024-03-12")
    await driver.findElement(By.css(".searchIcon")).click()
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".card:nth-child(1) span")).getText() == "test title75")
    assert(await driver.findElement(By.css(".card:nth-child(2) span")).getText() == "test title75")
    await driver.findElement(By.css(".btn-primary:nth-child(1)")).click()
    // //모달 date value는 2024
    {
      const value = await driver.findElement(By.id("addDate")).getAttribute("value")
      assert(value == "2024-03-12")
    }
    await driver.findElement(By.css(".btn-secondary")).click()
    await driver.findElement(By.css(".card:nth-child(2) .btn-primary")).click()
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("addDate"))), 3000)
    {
      const value = await driver.findElement(By.id("addDate")).getAttribute("value")
      assert(value == "2024-03-12")
    }
    await driver.findElement(By.css(".btn-close")).click()
    // // 삭제하기
    console.log("삭제하기")
    await driver.get("http://todo.wooyu.world/")
    const times = 2
    for(let i = 0; i < times; i++) {
      await driver.findElement(By.name("deleteBtn")).click()
      assert(await driver.switchTo().alert().getText() == "삭제하시겠습니까?")
      await driver.switchTo().alert().accept()
    }
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(!elements.length)
    }
  })
  it('TC00000076', async function() {
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title76")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-12")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.get("http://todo.wooyu.world/")
    await driver.wait(until.elementTextIs(await driver.findElement(By.css(".title")), 'To do list'), 30000)
    // //여기까지 전제조건
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    await driver.findElement(By.id("searchTitle")).click()
    await driver.findElement(By.id("searchTitle")).sendKeys("to do list76")
    await driver.findElement(By.id("searchDate")).click()
    await driver.findElement(By.id("searchDate")).sendKeys("002024-04-12")
    await driver.findElement(By.css(".searchIcon")).click()
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(!elements.length)
    }
    // // 삭제하기
    console.log("삭제하기")
    await driver.get("http://todo.wooyu.world/")
    await driver.findElement(By.name("deleteBtn")).click()
    assert(await driver.switchTo().alert().getText() == "삭제하시겠습니까?")
    await driver.switchTo().alert().accept()
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(!elements.length)
    }
  })
  it('TC00000077', async function() {
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title77")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-12")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.get("http://todo.wooyu.world/")
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("to do7 list7")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-13")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.wait(until.elementTextIs(await driver.findElement(By.css(".title")), 'To do list'), 30000)
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    // //여기까지 전제조건
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(elements.length)
    }
    await driver.findElement(By.id("searchTitle")).click()
    await driver.findElement(By.id("searchTitle")).sendKeys("test title77")
    await driver.findElement(By.id("searchDate")).click()
    await driver.findElement(By.id("searchDate")).sendKeys("002024-03-12")
    {
      const value = await driver.findElement(By.id("searchTitle")).getAttribute("value")
      assert(value == "test title77")
    }
    {
      const value = await driver.findElement(By.id("searchDate")).getAttribute("value")
      assert(value == "002024-03-12")
    }
    await driver.findElement(By.css(".searchIcon")).click()
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(!elements.length)
    }
    assert(await driver.findElement(By.css(".card:nth-child(1) span")).getText() == "test title77")
    await driver.findElement(By.css(".btn-primary:nth-child(1)")).click()
    // //모달 date value는 2024
    {
      const value = await driver.findElement(By.id("addDate")).getAttribute("value")
      assert(value == "2024-03-12")
    }
    {
      const value = await driver.findElement(By.id("exampleModalLabel")).getAttribute("value")
      assert(value == "test title77")
    }
    await driver.findElement(By.css(".btn-secondary")).click()
    // // 삭제하기
    console.log("삭제하기")
    await driver.get("http://todo.wooyu.world/")
    const times = 2
    for(let i = 0; i < times; i++) {
      await driver.findElement(By.name("deleteBtn")).click()
      assert(await driver.switchTo().alert().getText() == "삭제하시겠습니까?")
      await driver.switchTo().alert().accept()
    }
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(!elements.length)
    }
  })
  it('TC00000078', async function() {
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title78")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-12")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.get("http://todo.wooyu.world/")
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("to do7 list8")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-13")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.wait(until.elementTextIs(await driver.findElement(By.css(".title")), 'To do list'), 30000)
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    // //여기까지 전제조건
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(elements.length)
    }
    await driver.findElement(By.id("searchTitle")).click()
    await driver.findElement(By.id("searchTitle")).sendKeys("test ti")
    await driver.findElement(By.id("searchDate")).click()
    await driver.findElement(By.id("searchDate")).sendKeys("002024-03-12")
    await driver.findElement(By.css(".searchIcon")).click()
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(!elements.length)
    }
    assert(await driver.findElement(By.css(".card:nth-child(1) span")).getText() == "test title78")
    // //test ti 포함하는지 mcoah.js로 작성하여 확인
    console.log("test ti 포함하는지 mcoah.js로 작성하여 확인")
    await driver.findElement(By.css(".btn-primary:nth-child(1)")).click()
    // //모달 date value는 2024
    {
      const value = await driver.findElement(By.id("addDate")).getAttribute("value")
      assert(value == "2024-03-12")
    }
    {
      const value = await driver.findElement(By.id("exampleModalLabel")).getAttribute("value")
      assert(value == "test title78")
    }
    await driver.findElement(By.css(".btn-secondary")).click()
    // // 삭제하기
    console.log("삭제하기")
    await driver.get("http://todo.wooyu.world/")
    const times = 2
    for(let i = 0; i < times; i++) {
      await driver.findElement(By.name("deleteBtn")).click()
      assert(await driver.switchTo().alert().getText() == "삭제하시겠습니까?")
      await driver.switchTo().alert().accept()
    }
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(!elements.length)
    }
  })
  it('TC00000079', async function() {
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title79")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-12")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.get("http://todo.wooyu.world/")
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title79")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-13")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.wait(until.elementTextIs(await driver.findElement(By.css(".title")), 'To do list'), 30000)
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    // //여기까지 전제조건
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(elements.length)
    }
    await driver.findElement(By.id("searchTitle")).click()
    await driver.findElement(By.id("searchTitle")).sendKeys("test title79")
    await driver.findElement(By.id("searchDate")).click()
    await driver.findElement(By.id("searchDate")).sendKeys("002024-03-12")
    await driver.findElement(By.css(".searchIcon")).click()
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(!elements.length)
    }
    assert(await driver.findElement(By.css(".card:nth-child(1) span")).getText() == "test title79")
    await driver.findElement(By.css(".btn-primary:nth-child(1)")).click()
    // //모달 date value는 2024
    {
      const value = await driver.findElement(By.id("addDate")).getAttribute("value")
      assert(value == "2024-03-12")
    }
    {
      const value = await driver.findElement(By.id("exampleModalLabel")).getAttribute("value")
      assert(value == "test title79")
    }
    await driver.findElement(By.css(".btn-secondary")).click()
    // // 삭제하기
    console.log("삭제하기")
    await driver.get("http://todo.wooyu.world/")
    const times = 2
    for(let i = 0; i < times; i++) {
      await driver.findElement(By.name("deleteBtn")).click()
      assert(await driver.switchTo().alert().getText() == "삭제하시겠습니까?")
      await driver.switchTo().alert().accept()
    }
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(!elements.length)
    }
  })
  it('TC00000080', async function() {
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title80")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-12")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.get("http://todo.wooyu.world/")
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title80")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-13")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.wait(until.elementTextIs(await driver.findElement(By.css(".title")), 'To do list'), 30000)
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    // //여기까지 전제조건
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(elements.length)
    }
    await driver.findElement(By.id("searchTitle")).click()
    await driver.findElement(By.id("searchTitle")).sendKeys("test ti")
    await driver.findElement(By.id("searchDate")).click()
    await driver.findElement(By.id("searchDate")).sendKeys("002024-03-12")
    await driver.findElement(By.css(".searchIcon")).click()
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(!elements.length)
    }
    assert(await driver.findElement(By.css(".card:nth-child(1) span")).getText() == "test title80")
    // //test ti 포함하는지 mcoah.js로 작성하여 확인
    console.log("test ti 포함하는지 mcoah.js로 작성하여 확인")
    await driver.findElement(By.css(".btn-primary:nth-child(1)")).click()
    // //모달 date value는 2024
    {
      const value = await driver.findElement(By.id("addDate")).getAttribute("value")
      assert(value == "2024-03-12")
    }
    {
      const value = await driver.findElement(By.id("exampleModalLabel")).getAttribute("value")
      assert(value == "test title80")
    }
    await driver.findElement(By.css(".btn-secondary")).click()
    // // 삭제하기
    console.log("삭제하기")
    await driver.get("http://todo.wooyu.world/")
    const times = 2
    for(let i = 0; i < times; i++) {
      await driver.findElement(By.name("deleteBtn")).click()
      assert(await driver.switchTo().alert().getText() == "삭제하시겠습니까?")
      await driver.switchTo().alert().accept()
    }
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(!elements.length)
    }
  })
  it('TC00000081', async function() {
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title81")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-12")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.get("http://todo.wooyu.world/")
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("to do8 list1")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-12")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.wait(until.elementTextIs(await driver.findElement(By.css(".title")), 'To do list'), 30000)
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    // //여기까지 전제조건
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(elements.length)
    }
    await driver.findElement(By.id("searchTitle")).click()
    await driver.findElement(By.id("searchTitle")).sendKeys("test title81")
    await driver.findElement(By.id("searchDate")).click()
    await driver.findElement(By.id("searchDate")).sendKeys("002024-03-12")
    await driver.findElement(By.css(".searchIcon")).click()
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(!elements.length)
    }
    assert(await driver.findElement(By.css(".card:nth-child(1) span")).getText() == "test title81")
    await driver.findElement(By.css(".btn-primary:nth-child(1)")).click()
    // //모달 date value는 2024
    {
      const value = await driver.findElement(By.id("addDate")).getAttribute("value")
      assert(value == "2024-03-12")
    }
    {
      const value = await driver.findElement(By.id("exampleModalLabel")).getAttribute("value")
      assert(value == "test title81")
    }
    await driver.findElement(By.css(".btn-secondary")).click()
    // // 삭제하기
    console.log("삭제하기")
    await driver.get("http://todo.wooyu.world/")
    const times = 2
    for(let i = 0; i < times; i++) {
      await driver.findElement(By.name("deleteBtn")).click()
      assert(await driver.switchTo().alert().getText() == "삭제하시겠습니까?")
      await driver.switchTo().alert().accept()
    }
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(!elements.length)
    }
  })
  it('TC00000082', async function() {
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title82")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-12")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.get("http://todo.wooyu.world/")
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("to do8 list2")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-12")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.wait(until.elementTextIs(await driver.findElement(By.css(".title")), 'To do list'), 30000)
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    // //여기까지 전제조건
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(elements.length)
    }
    await driver.findElement(By.id("searchTitle")).click()
    await driver.findElement(By.id("searchTitle")).sendKeys("test ti")
    await driver.findElement(By.id("searchDate")).click()
    await driver.findElement(By.id("searchDate")).sendKeys("002024-03-12")
    await driver.findElement(By.css(".searchIcon")).click()
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(!elements.length)
    }
    assert(await driver.findElement(By.css(".card:nth-child(1) span")).getText() == "test title82")
    // //test ti 포함하는지 mcoah.js로 작성하여 확인
    console.log("test ti 포함하는지 mcoah.js로 작성하여 확인")
    await driver.findElement(By.css(".btn-primary:nth-child(1)")).click()
    // //모달 date value는 2024
    {
      const value = await driver.findElement(By.id("addDate")).getAttribute("value")
      assert(value == "2024-03-12")
    }
    {
      const value = await driver.findElement(By.id("exampleModalLabel")).getAttribute("value")
      assert(value == "test title82")
    }
    await driver.findElement(By.css(".btn-secondary")).click()
    // // 삭제하기
    console.log("삭제하기")
    await driver.get("http://todo.wooyu.world/")
    const times = 2
    for(let i = 0; i < times; i++) {
      await driver.findElement(By.name("deleteBtn")).click()
      assert(await driver.switchTo().alert().getText() == "삭제하시겠습니까?")
      await driver.switchTo().alert().accept()
    }
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(!elements.length)
    }
  })
  it('TC00000083', async function() {
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title83")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-12")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.get("http://todo.wooyu.world/")
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title83")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-12")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.wait(until.elementTextIs(await driver.findElement(By.css(".title")), 'To do list'), 30000)
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    // //여기까지 전제조건
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(elements.length)
    }
    await driver.findElement(By.id("searchTitle")).click()
    await driver.findElement(By.id("searchTitle")).sendKeys("test title83")
    await driver.findElement(By.id("searchDate")).click()
    await driver.findElement(By.id("searchDate")).sendKeys("002024-03-12")
    await driver.findElement(By.css(".searchIcon")).click()
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".card:nth-child(1) span")).getText() == "test title83")
    assert(await driver.findElement(By.css(".card:nth-child(2) span")).getText() == "test title83")
    await driver.findElement(By.css(".btn-primary:nth-child(1)")).click()
    // //모달 date value는 2024
    {
      const value = await driver.findElement(By.id("addDate")).getAttribute("value")
      assert(value == "2024-03-12")
    }
    {
      const value = await driver.findElement(By.id("exampleModalLabel")).getAttribute("value")
      assert(value == "test title83")
    }
    await driver.findElement(By.css(".btn-secondary")).click()
    await driver.wait(until.elementIsVisible(await driver.findElement(By.css(".card:nth-child(2) .btn-primary"))), 3000)
    await driver.findElement(By.css(".card:nth-child(2) .btn-primary")).click()
    {
      const value = await driver.findElement(By.id("exampleModalLabel")).getAttribute("value")
      assert(value == "test title83")
    }
    // //모달 date value는 2024
    {
      const value = await driver.findElement(By.id("addDate")).getAttribute("value")
      assert(value == "2024-03-12")
    }
    await driver.findElement(By.css(".btn-secondary")).click()
    // // 삭제하기
    console.log("삭제하기")
    await driver.get("http://todo.wooyu.world/")
    const times = 2
    for(let i = 0; i < times; i++) {
      await driver.findElement(By.name("deleteBtn")).click()
      assert(await driver.switchTo().alert().getText() == "삭제하시겠습니까?")
      await driver.switchTo().alert().accept()
    }
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(!elements.length)
    }
  })
  it('TC00000084', async function() {
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title84")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-12")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.get("http://todo.wooyu.world/")
    await driver.findElement(By.css(".bi-pencil-fill")).click()
    // 모달 나타날때까지 기다림
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("exampleModalLabel"))), 3000)
    await driver.findElement(By.id("exampleModalLabel")).click()
    await driver.findElement(By.id("exampleModalLabel")).sendKeys("test title84")
    await driver.findElement(By.id("addDate")).click()
    await driver.findElement(By.id("addDate")).sendKeys("002024-03-12")
    await driver.findElement(By.id("modalSaveBtn")).click()
    await driver.wait(until.elementTextIs(await driver.findElement(By.css(".title")), 'To do list'), 30000)
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    // //여기까지 전제조건
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(elements.length)
    }
    await driver.findElement(By.id("searchTitle")).click()
    await driver.findElement(By.id("searchTitle")).sendKeys("test ti")
    await driver.findElement(By.id("searchDate")).click()
    await driver.findElement(By.id("searchDate")).sendKeys("002024-03-12")
    await driver.findElement(By.css(".searchIcon")).click()
    {
      const elements = await driver.findElements(By.css(".card:nth-child(1) > .card-body"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".card:nth-child(2) > .card-body"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".card:nth-child(1) span")).getText() == "test title84")
    assert(await driver.findElement(By.css(".card:nth-child(2) span")).getText() == "test title84")
    // //test ti 포함하는지 mcoah.js로 작성하여 확인
    console.log("test ti 포함하는지 mcoah.js로 작성하여 확인")
    await driver.findElement(By.css(".btn-primary:nth-child(1)")).click()
    // //모달 date value는 2024
    {
      const value = await driver.findElement(By.id("addDate")).getAttribute("value")
      assert(value == "2024-03-12")
    }
    {
      const value = await driver.findElement(By.id("exampleModalLabel")).getAttribute("value")
      assert(value == "test title84")
    }
    await driver.findElement(By.css(".btn-secondary")).click()
    await driver.wait(until.elementIsVisible(await driver.findElement(By.css(".card:nth-child(2) .btn-primary"))), 3000)
    await driver.findElement(By.css(".card:nth-child(2) .btn-primary")).click()
    {
      const value = await driver.findElement(By.id("exampleModalLabel")).getAttribute("value")
      assert(value == "test title84")
    }
    // //모달 date value는 2024
    {
      const value = await driver.findElement(By.id("addDate")).getAttribute("value")
      assert(value == "2024-03-12")
    }
    await driver.findElement(By.css(".btn-secondary")).click()
    // // 삭제하기
    console.log("삭제하기")
    await driver.get("http://todo.wooyu.world/")
    const times = 2
    for(let i = 0; i < times; i++) {
      await driver.findElement(By.name("deleteBtn")).click()
      assert(await driver.switchTo().alert().getText() == "삭제하시겠습니까?")
      await driver.switchTo().alert().accept()
    }
    {
      const elements = await driver.findElements(By.css(".card-body"))
      assert(!elements.length)
    }
  })
})
